0. Instalar e importar NumPy

In [ ]:
%pip install numpy
import numpy as np # type: ignore

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


1. Creación de arrays

In [3]:
#Unidimensionales
array_unim = np.array([1,2,3,4,5])
array_unim

array([1, 2, 3, 4, 5])

In [4]:
#Bidimensionales
array_bidim = np.array([
    [1,2,3],
    [4,5,6]
])
array_bidim

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#Tridimensionales
array_tridim = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
array_tridim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

2. Propiedades de los arrays

In [7]:
# Atributos de unidimensionales
# forma, dimensiones, tipo de dato, tamaño y tipo de elemento
array_unim.shape, array_unim.ndim, array_unim.dtype, array_unim.size, type(array_unim)


((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [8]:
# Atributos de multidimensionales
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [13]:
#Antes de continuar instalamos he importamos pandas
%pip install pandas 
import pandas as pd # type: ignore

Note: you may need to restart the kernel to use updated packages.


In [14]:
# Convertir arreglo a dataframe
datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [15]:
# Arrays formados por unos
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#Arrays formados por ceros
ceros = np.zeros((2,4,3))
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
#Arrays con numeros en un rango y con un paso
array_rango = np.arange(0,100,5)
array_rango_2 = np.arange(0,100+1,5)
array_rango, array_rango_2

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
        85, 90, 95]),
 array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
         65,  70,  75,  80,  85,  90,  95, 100]))

In [33]:
# Arrays con numeros aleatorios enteros entre valores
array_randomint = np.random.randint(0,10,(2,5))
array_randomint 

array([[3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1]], dtype=int32)

In [29]:
# Arrays con numeros aleatorios decimales entre valores
array_randomdec = np.random.random((2,5))
array_randomdec 

array([[0.25192268, 0.10939226, 0.73871496, 0.28298865, 0.27109527],
       [0.45915752, 0.71261646, 0.94030055, 0.34717853, 0.28160627]])

In [32]:
# Los numeros aleatorios se genera a partir de una semilla
np.random.seed(42)
array_random_seed = np.random.randint(0,10,(2,5))
array_random_seed

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4]], dtype=int32)

4. Encontrar valores dentro de un arreglo

In [34]:
# Encontrar valores unicos
np.unique(array_random_seed)

array([2, 3, 4, 6, 7, 9], dtype=int32)

In [36]:
# Encontrar el valor de indice X
array_random_seed[1,0]

np.int32(9)

In [37]:
# Mostrar
array_random_prueba = np.random.randint(0,10,(5,5))
array_random_prueba

array([[4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3],
       [8, 1, 9, 8, 9]], dtype=int32)

In [38]:
array_random_prueba[:2]

array([[4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3]], dtype=int32)

In [39]:
array_random_prueba[1:3,:2]

array([[0, 9],
       [8, 2]], dtype=int32)

6. Operaciones con array

In [41]:
array_1 = np.random.randint(0,10,(3,4))
array_2 = np.ones((3,4))
array_1, array_2

(array([[5, 5, 9, 3],
        [5, 1, 9, 1],
        [9, 3, 7, 6]], dtype=int32),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [42]:
array_1 + array_2

array([[ 6.,  6., 10.,  4.],
       [ 6.,  2., 10.,  2.],
       [10.,  4.,  8.,  7.]])

In [43]:
array_3 = np.ones((4,3))
array_1 + array_3

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [44]:
array_3 = np.ones((4,3))
array_1 + array_3.T

array([[ 6.,  6., 10.,  4.],
       [ 6.,  2., 10.,  2.],
       [10.,  4.,  8.,  7.]])

In [47]:
array_1.flatten()

array([5, 5, 9, 3, 5, 1, 9, 1, 9, 3, 7, 6], dtype=int32)

In [48]:
array_tridim.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
np.sqrt(array_1)

array([[2.23606798, 2.23606798, 3.        , 1.73205081],
       [2.23606798, 1.        , 3.        , 1.        ],
       [3.        , 1.73205081, 2.64575131, 2.44948974]])

In [50]:
array_1.mean()

np.float64(5.25)

In [51]:
array_1.max(), array_1.min()

(np.int32(9), np.int32(1))

In [56]:
array_4 = np.random.randint(0,10,(3,4))
array_1, array_4

(array([[5, 5, 9, 3],
        [5, 1, 9, 1],
        [9, 3, 7, 6]], dtype=int32),
 array([[7, 1, 0, 6],
        [6, 7, 4, 2],
        [7, 5, 2, 0]], dtype=int32))

In [58]:
# Comparar arrays
array_5 = array_4 > array_1
array_5

array([[ True, False, False,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

7. ¿Porque NumPy?

In [65]:
import time
# Lista muy grande
lista_grande = list(range(10000000))
# Array muy grande
array_grande = np.array(lista_grande)

In [66]:
# Probamos a ver cuanto tarda en operar el cuadrado de todos los valores de la lista
inicio_lista = time.time()
for i in lista_grande:
    i ** 2
fin_lista = time.time()
print("Tiempo en procesar la lista: ", fin_lista - inicio_lista)

Tiempo en procesar la lista:  0.08199739456176758


In [68]:
# Probamos a ver cuanto tarda en operar el cuadrado de todos los valores de la lista
inicio_array = time.time()
resultado = array_grande ** 2
fin_array = time.time()
print("Tiempo en procesar la array: ", fin_array - inicio_array)

Tiempo en procesar la array:  0.006900787353515625


8. Concatenar, slicing, y trabajar con indices

In [69]:
# Concatenar
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a = [
    [1,2],
    [3,4]
]
b = [
    [5,6],
    [7,8]
]
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [71]:
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])